#cloud-config
autoinstall:
  version: 1
  user-data:
    users: [""]
    disable_root: false
  ssh:
    install-server: no
  storage:
    layout:
      name: lvm
      password: ubuntu # Change this to your desired password
  keyboard:
    layout: de
  locale: en_US
  timezone: "Europe/Berlin"
  updates: security
  shutdown: reboot
  packages:
    - curl
    - git
    - wget
    - gpg
  snaps: # Install apps from this catalog: https://snapcraft.io/store
    # - name: code
    #   classic: true
    - name: postman
    # - name: powershell
    #   classic: true
    # - name: sublime-text
    #   classic: true
  late-commands:
    # Password Policy
    - curtin in-target --target=/target -- cp /etc/security/pwquality.conf /etc/security/pwquality.conf.bak
    - curtin in-target --target=/target -- sh -c 'echo "minlen = 10" >> /etc/security/pwquality.conf'
    - curtin in-target --target=/target -- sh -c 'echo "ucredit = -1" >> /etc/security/pwquality.conf'
    - curtin in-target --target=/target -- sh -c 'echo "dcredit = -1" >> /etc/security/pwquality.conf'
    - curtin in-target --target=/target -- sh -c 'echo "lcredit = -1" >> /etc/security/pwquality.conf'
    - curtin in-target --target=/target -- sh -c 'echo "difok = 3" >> /etc/security/pwquality.conf'
    - curtin in-target --target=/target -- sh -c 'echo "reject_username = 1" >> /etc/security/pwquality.conf'
    - curtin in-target --target=/target -- sh -c 'echo "enforce_for_root = 1" >> /etc/security/pwquality.conf'
  
    # Install Microsoft Intune Portal
    # - curtin in-target --target=/target -- mkdir -p /tmp/microsoft
    # - curtin in-target --target=/target -- sh -c 'cd /tmp/microsoft && curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg'
    # - curtin in-target --target=/target -- install -o root -g root -m 644 /tmp/microsoft/microsoft.gpg /usr/share/keyrings/microsoft.gpg
    # - curtin in-target --target=/target -- sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/24.04/prod noble main" > /etc/apt/sources.list.d/microsoft-ubuntu-noble-prod.list'
    # - curtin in-target --target=/target -- apt-get update
    # - curtin in-target --target=/target -- apt-get install -y intune-portal

    # Install Microsoft Edge
    # - curtin in-target --target=/target -- sh -c 'curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg'
    # - curtin in-target --target=/target -- install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
    # - curtin in-target --target=/target -- sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
    # - curtin in-target --target=/target -- rm microsoft.gpg
    # - curtin in-target --target=/target -- apt-get update
    # - curtin in-target --target=/target -- apt-get install -y microsoft-edge-stable

    # Remove bloatware
    - curtin in-target --target=/target -- apt-get purge -y libreoffice-common
    - curtin in-target --target=/target -- apt-get purge -y libreoffice*
    - curtin in-target --target=/target -- apt-get purge -y remmina*
    - curtin in-target --target=/target -- apt-get purge -y transmission*

    # Clean up
    - curtin in-target --target=/target -- apt-get autoremove -y
    - curtin in-target --target=/target -- apt-get clean
    - curtin in-target --target=/target -- rm -rf /tmp/microsoft
