#cloud-config
autoinstall:
  version: 1
  user-data:
    users: [""]
    disable_root: false
  ssh:
    install-server: no
  storage:
    layout:
      name: lvm
      password: ubuntu # Change this to your desired password
  keyboard:
    layout: de
  locale: en_US
  timezone: "Europe/Berlin"
  updates: security
  shutdown: reboot
  packages:
    - curl
    - git
    - wget
    - gpg
  late-commands:
    # Clean up
    - curtin in-target --target=/target -- apt-get autoremove -y
    - curtin in-target --target=/target -- apt-get clean
    - curtin in-target --target=/target -- rm -rf /tmp/microsoft
